# 🐼 Pandas I: Fundamentos y Manipulación de Datos

Esta sesión está pensada para un grupo con ritmo ágil.

## Objetivo
Pasar de archivos crudos a un flujo real de trabajo con pandas:
- cargar,
- inspeccionar,
- seleccionar,
- filtrar,
- transformar,
- ordenar,
- exportar.

## Estructura
Vamos a trabajar en bloques cortos de demostración + ejercicio práctico.

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

np.random.seed(42)

## 1️⃣ Series: la estructura más simple

Una **Series** es un array unidimensional con índice.

Puedes verla como una columna suelta con etiquetas.

In [3]:
values = [10, 20, 30, 40]
s_list = pd.Series(values, index=['a', 'b', 'c', 'd'])

data_dict = {'Apple': 100, 'Banana': 200, 'Cherry': 150}
s_dict = pd.Series(data_dict)

print("Series from list:", s_list)
print()
print("Series from dict:", s_dict)
print()
print("Index:", s_dict.index)
print("Values:", s_dict.values)

Series from list: a    10
b    20
c    30
d    40
dtype: int64

Series from dict: Apple     100
Banana    200
Cherry    150
dtype: int64

Index: Index(['Apple', 'Banana', 'Cherry'], dtype='str')
Values: [100 200 150]

### 🧠 Ejercicio 1: crea e inspecciona una Series

1. Crea una Series llamada `temperatures` con los valores `18, 21, 19, 24`.
2. Usa como índice `"Mon", "Tue", "Wed", "Thu"`.
3. Muestra el valor de `"Wed"`.
4. Muestra su índice y sus valores.

In [9]:
# Your code here
#1. Crea una Series llamada `temperatures` con los valores `18, 21, 19, 24`.
temperatures = [18, 21, 19, 24]
#2. Usa como índice `"Mon", "Tue", "Wed", "Thu"`.
temperatures = pd.Series(values, index=["Mon", "Tue", "Wed", "Thu"])
temperatures = pd.Series(temperatures)
print(temperatures)
print(temperatures.index)
#3. Muestra el valor de `"Wed"`.
print("Valor de Wed: ",temperatures["Wed"])
#4. Muestra su índice y sus valores.
print("Series from temperature:\n", temperatures)

Mon    10
Tue    20
Wed    30
Thu    40
dtype: int64
Index(['Mon', 'Tue', 'Wed', 'Thu'], dtype='str')
Valor de Wed:  30
Series from temperature:
 Mon    10
Tue    20
Wed    30
Thu    40
dtype: int64

## 2️⃣ DataFrames: la tabla de datos

Un **DataFrame** es una estructura bidimensional con filas y columnas.

Normalmente se crea a partir de un diccionario de listas.

In [10]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Paris', 'London', 'Tokyo'],
    'Salary': [50000, 60000, 70000, 80000],
}

df_manual = pd.DataFrame(data)
display(df_manual)
print("Shape:", df_manual.shape)

      Name  Age      City  Salary
0    Alice   25  New York   50000
1      Bob   30     Paris   60000
2  Charlie   35    London   70000
3    David   40     Tokyo   80000

Shape: (4, 4)

### 🧠 Ejercicio 2: crea un DataFrame manualmente

Crea un DataFrame llamado `df_products` con estas columnas:
- `Product`
- `Price`
- `Stock`

Usa al menos 4 filas.

Después:
1. muéstralo,
2. imprime `shape`,
3. imprime solo los nombres de columnas.

In [11]:
# Your code here
data2 = {
    "Producto" : ["cuchillo","tenedor","cuchara","plato"],
    "Precio" : [2, 4, 3, 12],
    "Stock" : [200, 198, 240, 400]
}

df_productos = pd.DataFrame(data2)

display(df_productos)

print(f"Filas y columnas: {df_productos.shape}")

print(f"Nombre de las columnas: {df_productos.columns}")

   Producto  Precio  Stock
0  cuchillo       2    200
1   tenedor       4    198
2   cuchara       3    240
3     plato      12    400

Filas y columnas: (4, 3)
Nombre de las columnas: Index(['Producto', 'Precio', 'Stock'], dtype='str')

## 3️⃣ Lectura de archivos con pandas

Aquí es donde pandas empieza a ahorrar muchísimo tiempo.

Hoy vamos a cargar:
- CSV,
- JSON simple,
- JSON con lista de registros,
- Excel.

In [13]:
df_csv = pd.read_csv('personas.csv')
df_json_list = pd.read_json('personas.json')
df_json_single = pd.read_json('persona.json')

print("CSV loaded:")
display(df_csv)
print("JSON list loaded:")
display(df_json_list)
print("JSON single object loaded:")
display(df_json_single)

try:
    df_excel = pd.read_excel('Book1.xlsx')
    print("Excel loaded:")
    display(df_excel.head())
except Exception as exc:
    print("Excel could not be loaded:", exc)

CSV loaded:

  Nombre  Edad        Ciudad
0    Ana    25          Lima
1   Luis    30        Bogotá
2  María    22  Buenos Aires

JSON list loaded:

  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]
2  María    22             [arte, cine]

JSON single object loaded:

  nombre  edad     intereses
0    Ana    25       lectura
1    Ana    25  programación

Excel loaded:

   nombre  edad  altura
0    Alex    25     180
1  Alonso    26     187
2   María    24     175
3   Paula    23     160

### 🧠 Ejercicio 3: carga y compara formatos

1. Carga `personas.csv` en un DataFrame llamado `people_csv`.
2. Carga `personas.json` en un DataFrame llamado `people_json`.
3. Muestra `shape` de ambos.
4. Muestra las 2 primeras filas de cada uno.

In [14]:
# Your code here
people_csv = pd.read_csv("personas.csv")

people_json = pd.read_json("personas.json")

print(f" shape de personas en csv: {people_csv.shape}")

print(f" shape de personas en json: {people_json.shape}")

display(people_csv.head(2))

display(people_json.head(2))

 shape de personas en csv: (3, 3)
 shape de personas en json: (3, 3)

  Nombre  Edad  Ciudad
0    Ana    25    Lima
1   Luis    30  Bogotá

  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]

## 4️⃣ Inspección: mirar antes de tocar

Antes de hacer análisis o limpieza, hay que responder rápido:
- ¿cuántas filas y columnas hay?
- ¿qué tipos tengo?
- ¿qué aspecto tienen los datos?

In [17]:
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
)

display(df_large.head(3))
display(df_large.tail(3))
print("Shape:", df_large.shape)
print("Rows:", df_large.shape[0])
print("Columns:", df_large.shape[1])
print()
df_large.info()
print("describe:")
display(df_large.describe())

    A   B   C   D   E
0  75  25  15  50  85
1  56  28  77  91  68
2  46  93  61  68  75

     A   B   C   D   E
97  16  85  89  43  24
98  16  12  83  24  67
99   9  66  17  99  85

Shape: (100, 5)
Rows: 100
Columns: 5

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       100 non-null    int32
 1   B       100 non-null    int32
 2   C       100 non-null    int32
 3   D       100 non-null    int32
 4   E       100 non-null    int32
dtypes: int32(5)
memory usage: 2.1 KB
describe:

                A           B           C           D           E
count  100.000000  100.000000  100.000000  100.000000  100.000000
mean    43.230000   50.930000   52.520000   47.180000   53.050000
std     30.434847   28.224302   31.042649   30.307308   27.265761
min      0.000000    0.000000    0.000000    0.000000    3.000000
25%     16.000000   26.750000   21.750000   23.750000   33.250000
50%     36.000000   55.000000   58.000000   46.000000   53.500000
75%     73.500000   73.000000   81.250000   71.500000   74.000000
max     98.000000   99.000000   99.000000   99.000000   99.000000

### 🧠 Ejercicio 4: radiografía rápida del DataFrame

Usando `df_large`:
1. muestra las 5 primeras filas,
2. muestra las 5 últimas,
3. imprime `shape`,
4. imprime solo el número de filas usando `shape[0]`,
5. imprime `dtypes`.

In [ ]:
# Your code here

     B   E
0   25  85
1   28  68
2   93  75
3   89  84
4   99  22
..  ..  ..
95  37  63
96  27  56
97  85  24
98  12  67
99  66  85

[100 rows x 2 columns]

     A   B   C   D   E
50  75  23  27   7  91
51  35  89   7  57  59
52  49  27  91  40  99
53  63  26  62  16  72
54  32  83  76  91  28
55  12  45  34   5  81

np.int32(75)

     C   D
10  60  50
11  64  32
12  43  28
13  45   1
14  89   7
15  89  33

## 5️⃣ Selección e indexación

Aquí está uno de los núcleos de la clase:
- `df['columna']` para columnas,
- `df[['col1', 'col2']]` para varias columnas,
- `.iloc` por posición,
- `.loc` por etiqueta.

In [21]:
col_a = df_large['A']
cols_subset = df_large[['A', 'C', 'E']]

display(cols_subset.head(3))
display(df_large.iloc[0:5, 0:3])
display(df_large.loc[0:5, ['A', 'D']])
print("Value at iloc[10, 2]:", df_large.iloc[10, 2])
print("Value at loc[0, 'A']:", df_large.loc[0, 'A'])

    A   C   E
0  75  15  85
1  56  77  68
2  46  61  75

    A   B   C
0  75  25  15
1  56  28  77
2  46  93  61
3  15  89  89
4  38  99  32

    A   D
0  75  50
1  56  91
2  46  68
3  15  47
4  38  93
5   9  33

Value at iloc[10, 2]: 60
Value at loc[0, 'A']: 75

### 🧠 Ejercicio 5: selección

Usando `df_large`:
1. selecciona las columnas `B` y `E`,
2. muestra las filas 50 a 55 usando `.iloc`,
3. muestra el valor de la fila `0` y la columna `A` usando `.loc`,
4. selecciona filas 10 a 15 y columnas `C` y `D`.

In [22]:
# Your code here
display(df_large[['B', 'E']])

display(df_large.iloc[50:56, :])

display(df_large.loc[0, 'A'])

display(df_large.loc[10:15, ['C', 'D']])

     B   E
0   25  85
1   28  68
2   93  75
3   89  84
4   99  22
..  ..  ..
95  37  63
96  27  56
97  85  24
98  12  67
99  66  85

[100 rows x 2 columns]

     A   B   C   D   E
50  75  23  27   7  91
51  35  89   7  57  59
52  49  27  91  40  99
53  63  26  62  16  72
54  32  83  76  91  28
55  12  45  34   5  81

np.int32(75)

     C   D
10  60  50
11  64  32
12  43  28
13  45   1
14  89   7
15  89  33

## ☕ Descanso sugerido (15 min)

Aquí ya deberían saber cargar, inspeccionar y seleccionar.

## 6️⃣ Filtrado y transformación

El patrón más común en trabajo real es:
1. filtrar filas,
2. crear columnas nuevas,
3. volver a filtrar,
4. quedarte solo con lo útil.

In [23]:
mask = df_large['A'] > 50
filtered_df = df_large[mask]

print("Original rows:", df_large.shape[0])
print("Filtered rows:", filtered_df.shape[0])

complex_filter = df_large[(df_large['A'] > 50) & (df_large['B'] < 20)]
display(complex_filter.head())

df_large['Suma'] = df_large['A'] + df_large['B']
display(df_large.head())

Original rows: 100
Filtered rows: 39

     A   B   C   D   E
6   94   9  18  57  95
8   79   1  91  31  90
26  82  15  68  98  11
61  98   0  20  54   5
66  76   3  61  64  31

    A   B   C   D   E  Suma
0  75  25  15  50  85   100
1  56  28  77  91  68    84
2  46  93  61  68  75   139
3  15  89  89  47  84   104
4  38  99  32  93  22   137

### 🧠 Ejercicio 6: máscaras y columnas nuevas

Usando `df_large`:
1. crea una columna `Total_AB` con `A + B`,
2. filtra filas con `A > 50`,
3. filtra filas con `A > 50` y `B < 20`,
4. muestra solo las columnas `A`, `B` y `Total_AB` del resultado filtrado.

In [24]:
# Your code here
df_large_copy = df_large[['A', 'B']]
df_large_copy['Total_AB'] = df_large_copy['A'] + df_large_copy['B']

new_df_large = df_large_copy[(df_large_copy['A'] > 50) & (df_large_copy['B'] < 20)]

display(new_df_large[['A', 'B', 'Total_AB']])

     A   B  Total_AB
6   94   9       103
8   79   1        80
26  82  15        97
61  98   0        98
66  76   3        79
92  85  13        98

## 7️⃣ Ordenación

Después de seleccionar y filtrar, normalmente queremos ordenar resultados.

Podemos ordenar por una o varias columnas, y decidir el sentido de cada una.

In [25]:
df_sorted = df_large.sort_values(by='A', ascending=True)
df_multi_sort = df_large.sort_values(by=['A', 'B'], ascending=[False, True])

display(df_sorted.head())
display(df_multi_sort.head())

    A   B   C   D   E  Suma
86  0   4  11  89  45     4
7   0  68   3  15  23    68
41  0   2  76  91  61     2
63  2  52  22  52  36    54
48  2  15  86  56  74    17

     A   B   C   D   E  Suma
61  98   0  20  54   5    98
91  98  51  78  46  55   149
6   94   9  18  57  95   103
70  93  56  16  46  22   149
83  92  31  49  60  50   123

### 🧠 Ejercicio 7: ordena resultados

1. Ordena `df_large` por la columna `A` de mayor a menor.
2. Ordena `df_large` por `A` descendente y `B` ascendente.
3. Muestra las 5 primeras filas de cada resultado.

In [29]:

print("ordena df_large por la columna A de mayor a menor")
df_sorted = df_large.sort_values(by = "A", ascending = False)
display(df_sorted.head())
print("Aqui se ordena por A descendente y B ascendente")
df_multi_sort = df_large.sort_values(by = ["A", "B"], ascending = [False, True])
display(df_multi_sort.head())

ordena df_large por la columna A de mayor a menor

     A   B   C   D   E  Suma
2   97  58  55  58  69   155
30  96  24  16  96  65   120
46  96  59  42  75  99   155
87  95  80  80  13   8   175
20  93  94  48  68  61   187

Aqui se ordena por A descendente y B ascendente

     A   B   C   D   E  Suma
2   97  58  55  58  69   155
30  96  24  16  96  65   120
46  96  59  42  75  99   155
87  95  80  80  13   8   175
9   93  50  61  56  65   143

## 🏆 Práctica Final

Usando `df_large`:

1. Crea una nueva columna llamada `Suma` que sea `A + B`.
2. Filtra las filas donde `Suma` sea mayor a `100`.
3. Quédate solo con las columnas `A`, `B`, `C` y `Suma`.
4. Ordena el resultado por la columna `C` de forma descendente.
5. Guarda el resultado en un archivo `resultado.csv`.

In [ ]:
# Your solution here
df_large = pd.DataFrame(
    np.random.randint(0, 100, size=(100, 5)),
    columns=['A', 'B', 'C', 'D', 'E']
    )

df_large["Suma"] = df_large["A"] + df_large["B"]
print(df_large)
#Filtramos por filas donde suma sea mayor que 100
df_filter = df_large[df_large["Suma"]>100]
#display(df_filter)

#Nos quedamos solo con ABC y SUMA
df_final = df_large[["A", "B", "C", "Suma"]]
#Se ordena por columna C Descendente
df_final = df_final.sort_values(by = "C", ascending=False)
#Aqui se guarda a csv
df_final.to_csv("df_final.csv", index=False)
display(df_final)

     A   B   C   D   E  Suma
0   33   7  39  82  41    40
1   40   5  51  25  63    45
2   97  58  55  58  69   155
3   32  52  21  20  69    84
4   69   3  93  74  61    72
..  ..  ..  ..  ..  ..   ...
95  11  52  70   9  44    63
96  16  25  84  91  61    41
97  45  63   1  53  64   108
98  50  52  35  25  28   102
99  20  10  39  10  35    30

[100 rows x 6 columns]

     A   B   C  Suma
91  84  41  99   125
38  30  46  99    76
85  52  43  98    95
22  33  75  98   108
35  37  56  96    93
..  ..  ..  ..   ...
97  45  63   1   108
13  11  46   0    57
69  62   3   0    65
67  18  17   0    35
63  48  70   0   118

[100 rows x 4 columns]